### ISSUE TITLE
DASKR JuliaDiffEq common interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DASKR.jl#1]
Conversation starts here: https://github.com/tshort/Sims.jl/issues/69

>It has a crude/partial common API interface, but I didn't know what I was doing. I mainly copied the Sundials function.

I'll submit some PRs.

>The common API doesn't support events. I think callbacks may still be a work in progress.

Yes. That is a big issue right now that we don't quite know how to solve. Maybe separating callback and event interfaces would do better than the current proposal of trying to have a common callback interface? The problem is that different packages need/can have very different code injected in via callbacks, so that's hard to standardize.

https://github.com/JuliaDiffEq/Roadmap/issues/10

>Also, it'll be challenging for the common API to handle things like a banded jacobian (not that we handle that now, but maybe someday).

Is passing this information as part of the algorithm type not possible (like how Sundials does it)? I see you have a flag for `:dense` which isn't used, so I guess the problem is more subtle (probably to do with the interop?).

**Comment by tshort** [comment]
Passing that info should be possible. I'm just not sure the different jacobian flavors would be treated the same in different solvers. Anyway, that's still ahead. I have several flags in the common interface that don't do anything.

**Comment by ChrisRackauckas** [comment]
Hey, here's the current state of the callbacks:

https://github.com/JuliaDiffEq/Roadmap/issues/10#issuecomment-267875728

Feel free to give your input on whether this works for you.

**Comment by ChrisRackauckas** [comment]
Details on callback can be their own thread.
