### ISSUE TITLE
Problem with types when dealing with DAEs which explicitly conatin the time

### ISSUE THREAD

**Issue by wg030** [JuliaDiffEq/DASKR.jl#22]
I have just figured out that a problem will occur if your DAE System contains the time explicitly.
For illustration purposes a slightly modified the code example from the package description so that you can reproduce the error. The Problem seems to be that the time is not of type Float64 but rather of type Array{Float64,1}, which contains one single element. This means that `t` is something like
`t = [1234.56]` instead of `t = 1234.56`.

Here is the example code:

    using DASKR
    u0 = [1.0, 0, 0]
    du0 = [-0.04, 0.04, 0.0]
    tspan = (0.0,100000.0)

    function resrob(tres, y, yp, r)
        #tres = tres[1]         # using this line in your code is a quick fix

        r[1]  = -0.04*y[1] + 1.0e4*y[2]*y[3]
        r[2]  = -r[1] - 3.0e7*y[2]*y[2] - yp[2]
        r[1] -=  yp[1]
        # the modification of the following line yields the error:
        # Cannot `convert` an object of type Array{Float64,1}
        # to an object of type Float64
        r[3]  =  y[1] + y[2] + y[3] - (1.0 + tres/100000.0)
    end

    prob = DAEProblem(resrob,u0,du0,tspan)
    sol = solve(prob, daskr())

**Comment by ChrisRackauckas** [comment]
Hmm, I tried making it pass only the value but it stalls because the C FFI part wants a reference. @tshort do you know why it wants a reference instead of just a value?

**Comment by ChrisRackauckas** [comment]
Fixed via https://github.com/JuliaDiffEq/DASKR.jl/commit/952499d87593d6d2b6453dfb418590d9aa006fec . Will tag soon.
