### ISSUE TITLE
What is `isdiff`?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DASKR.jl#4]
Can you explain what `isdiff` does?

**Comment by tshort** [comment]
That specifies whether variables are differential or purely algebraic. DASSL uses this for initialization and error checking under some conditions.

https://github.com/JuliaDiffEq/DASKR.jl/blob/master/src/core.jl#L613-L618

Sundials has something similar. It's the `diffstates` keyword argument in the simple interface.

Anyway, the name `diffstates` is probably better. I didn't see that before.

**Comment by ChrisRackauckas** [comment]
This is something we might want to handle in the problem type instead @mauro3

**Comment by mauro3** [comment]
We could but I think this is fine as an option too.
