### ISSUE TITLE
Register and tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DASKR.jl#6]
Of course, there's always more to do, but I think this library is ready for its first tag. What do you think?

**Comment by tshort** [comment]
+1

**Comment by tshort** [comment]
Can we set up JuliaDiffEq with attobot? That way, we could register and release updates just by tagging. I tried, but I don't have permissions to do this for DASKR.

**Comment by ChrisRackauckas** [comment]
My bad, though you had admin privileges here. I upped your privileges. You can set it up with attobot if you want. I tag so often that I'll probably stick with how I do it.

Closing this since the registration went through.
